### ISSUE TITLE
ui: user interface to be aware of users logging in through social networks

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-ui#92]
Currently, when one tries to log in with social network accounts gets this after authorising:

![image](https://user-images.githubusercontent.com/9035606/79753264-eb181f80-8315-11ea-9395-0a381b9a3905.png)

**Comment by diegodelemos** [comment]
Invenio throws the following error:
```console
[2020-04-20 11:14:57,952] WARNING in handlers: Identity class Unverified External is not one of [CERN RegisteredCERN Shared]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/invenio_oauthclient/handlers.py", line 225, in inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/invenio_oauthclient/handlers.py", line 286, in authorized_signup_handler
    account_info = handlers['info'](resp)
  File "/usr/local/lib/python3.6/site-packages/invenio_oauthclient/handlers.py", line 493, in inner
    return f(remote, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/invenio_oauthclient/contrib/cern.py", line 312, in account_info
    identity_class, ''.join(valid_identities)), remote, resp, )
invenio_oauthclient.errors.OAuthCERNRejectedAccountError: ('Identity class Unverified External is not one of [CERN RegisteredCERN Shared]', <flask_oauthlib.client.OAuthRemoteApp object at 0x7fdae7705240>,
```
